<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CIT-2510 Webpage</title>
  <style>
    body {
      background-color: #f0f0f0; 
      font-family: Arial, sans-serif;
      text-align: center;
      margin: 0;
      padding: 0;
    }
    .container {
      max-width: 600px;
      margin: 100px auto;
      padding: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Welcome to Raafay Mohammed and Syed Irfan’s webpage!</h1>
    <p>This webpage was made for the CIT-2510 class project for part 4 through Container Instances</p>
  </div>
</body>
</html>
